spring.application.name=ecommerce

server.port=7003
server.address=0.0.0.0

# ================= DATABASE (Railway MySQL) =================
spring.datasource.url=jdbc:mysql://maglev.proxy.rlwy.net:43715/railway
spring.datasource.username=root
spring.datasource.password=YvVFVvSUTflllGtPhggAQaaSkDzRdEag
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ================= JPA =================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect